services:
  db:
    image: 'postgres:17.2'
    container_name: postgres-17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    volumes:
      - ./db-data:/var/lib/postgresql/data/